services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: build
    ports:
      - "8080:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - backend
    networks:
      - app-network
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "localhost:host-gateway"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/app
      - /app/node_modules
      - db-data:/app/database
    networks:
      - app-network
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "localhost:host-gateway"

networks:
  app-network:
    driver: bridge

volumes:
  db-data: 