apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: carro-vendido-api-pvc
  labels:
    app: carro-vendido-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard 