apiVersion: v1
kind: Secret
metadata:
  name: carro-vendido-secrets
type: Opaque
stringData:
  DATABASE_URL: "file:./dev.db"
  JWT_SECRET: "super-secret-jwt-key-change-in-production"
  MERCADO_PAGO_ACCESS_TOKEN: "TEST-1234567890123456-012345-abcdef0123456789abcdef0123456789-123456789" 